trigger:
- main
stages:
  - stage: "BuildDisk"
    displayName: "This is my Build"
    jobs:
      - job: buildjob
        displayName: 'BuildDisk'
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'nov-azdevops25'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: 'az disk create -g rectus50009 -n azdisk1000 --size-gb 10 --location eastus2 --sku Standard_LRS'