trigger:
- main
stages:
  - stage: "Build"
    displayName: "This is my Build"
    jobs:
      - job: buildjob
        displayName: 'Build and Run Tests'
        steps:
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'vimal-conn2025-june'
            ScriptType: 'InlineScript'
            Inline: 'echo "hello"'